### ISSUE TITLE
Arm SDL2/GLES high CPU usage (Odroid C1, libMali.so)

### ISSUE THREAD

**Issue by MagaTailor** [swatteau/sokoban-rs#2]
It's probably not specific to sokoban-rs but do please have a look at raw callgrind output:

https://gist.github.com/petevine/c1ad55dcd1216737f73a

Thanks!

**Comment by swatteau** [comment]
Well, in fact is is specific to sokoban-rs. Events coming from the event pump are polled instead of being waited for. Therefore, the screen is redrawn continuously in the main loop. I'm going to fix this.

**Comment by MagaTailor** [comment]
Much better :) Thx!
